name: Java CI

on: [push]

jobs:
  test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn verify --file pom.xml -DskipTests

      - name: Test with Maven
        run: mvn test --file pom.xml

  terraform:
    name: 'Provision and Deploy'
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Working Directory (Terraform)
        run: pwd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: echo 'Invalid Format:' && terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve